---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r, include=FALSE}
data("instacart")

instacart = 
  instacart %>% 
  select(aisle, add_to_cart_order, days_since_prior_order, order_number, reordered, department) %>% 
  filter( 
    department == "dairy eggs")
  
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart A

```{r}

instacart %>% 
  plot_ly(x = ~add_to_cart_order, y = ~days_since_prior_order, type = "scatter", mode = "markers",
    color = ~aisle, alpha = 0.5)

```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  mutate(aisle = fct_reorder(aisle, order_number)) %>%
  plot_ly(y = ~order_number, color = ~aisle, type = "box", colors = "viridis")
```

### Chart C

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```

